Repository COS301-SE-2022/TradeSim, pull requests merged in 2022-09, with the labels that each got.

#162 Created News Column on Home Page
  apps/client/static/home.js
  apps/client/templates/home.html
Labels: priority:medium, Frontend

#164 Added Export Feature & Fixed News Icon Overlap
  apps/client/static/addETF.js
  apps/client/static/compare.js
  apps/client/static/home.js
  apps/client/templates/addETF.html
Labels: priority:medium, Frontend

#165 Added Loaders to Pages
  apps/client/static/compare.js
  apps/client/static/home.js
  apps/client/static/styles/main.css
  apps/client/static/styles/ticker.css
  apps/client/static/ticker.js
  apps/client/templates/compare-date.html
  apps/client/templates/home.html
  apps/client/templates/ticker.html
Labels: priority:medium, Frontend

#167 Updated Ticker Page
  apps/client/static/styles/ticker.css
  apps/client/static/ticker.js
  apps/client/templates/ticker.html
Labels: priority:medium, Frontend

#169 Updated Compare Page
  apps/client/static/addETF.js
  apps/client/static/compare.js
  apps/client/static/styles/main.css
  apps/client/static/styles/ticker.css
  apps/client/templates/addETF.html
  apps/client/templates/compare-date.html
Labels: priority:medium, Frontend

#170 Added Export Feature and Resized Pages
  apps/client/static/addETF.js
  apps/client/static/styles/main.css
  apps/client/templates/addETF.html
  apps/client/templates/addRule.html
  apps/client/templates/compare-date.html
  apps/client/templates/home.html
  apps/client/templates/ticker.html
Labels: priority:medium, Frontend

#171 Update home page
  apps/client/static/home.js
  apps/client/templates/home.html
Labels: priority:high, Frontend

#172 added container
  apps/client/templates/ticker.html
Labels: priority:medium, Frontend

#175 Created Cards if there are reconsider periods
  apps/client/static/compare.js
  apps/client/static/home.js
  apps/client/static/styles/main.css
  apps/client/static/styles/ticker.css
  apps/client/static/ticker.js
  apps/client/templates/addETF.html
  apps/client/templates/addRule.html
  apps/client/templates/compare-date.html
  apps/client/templates/home.html
  apps/client/templates/ticker.html
Labels: priority:medium, Frontend

#177 Changed Cards to Collapsible
  apps/client/static/compare.js
  apps/client/static/styles/main.css
  apps/client/templates/compare-date.html
Labels: priority:medium, Frontend

#178 Added Import and Export Features
  apps/client/static/addETF.js
  apps/client/static/styles/main.css
  apps/client/templates/addETF.html
  apps/client/templates/addRule.html
Labels: priority:medium, Frontend

#179 Added Collapsible on Home Page
  apps/client/static/rules.js
  apps/client/static/styles/main.css
  apps/client/templates/addRule.html
  apps/client/templates/home.html
Labels: priority:medium, Frontend

#180 Added login alerts and Added placeholder for users with no ETFS
  apps/client/static/home.js
  apps/client/static/login.js
  apps/client/static/register.js
  apps/client/static/styles/login.css
  apps/client/static/styles/main.css
  apps/client/templates/home.html
Labels: priority:medium, Frontend

#181 Added Responsiveness
  apps/client/static/styles/login.css
  apps/client/templates/compare-date.html
  apps/client/templates/home.html
  apps/client/templates/login.html
  apps/client/templates/signup.html
  apps/client/templates/ticker.html
Labels: priority:medium, Frontend

#182 (Backend) : Implementation and debugging
  apps/Backend/AiFactor.py
  apps/Backend/Backend.py
  apps/Backend/ETF.py
  apps/Backend/__pycache__/AiFactor.cpython-39.pyc
  apps/Backend/__pycache__/ETF.cpython-39.pyc
  apps/Backend/__pycache__/apiCalls.cpython-39.pyc
  apps/Backend/apiCalls.py
Labels: enhancement, priority:high, Backend

#185 (Implementation) : Return functionality for the AI
  apps/Backend/AiFactor.py
  apps/Backend/ETF.py
  apps/Backend/__pycache__/AiFactor.cpython-39.pyc
  apps/Backend/__pycache__/ETF.cpython-39.pyc
Labels: Backend

#188 (Backend) : Fixed and added Test
  .github/workflows/BuildBE.yml
  apps/Backend/dbpass.py
  apps/Backend/unitTesting.py
Labels: priority:high, Backend, CI/CD, Testing

#194 (Backend) : Added Testing and debugging
  .gitignore
  apps/Backend/AiFactor.py
  apps/Backend/AutomatedTesting.py
  apps/Backend/Backend.py
  apps/Backend/ETF.py
  apps/Backend/IntegrationTesting.py
  apps/Backend/Notes For Prioritize
  apps/Backend/__pycache__/AiFactor.cpython-39.pyc
  apps/Backend/__pycache__/ETF.cpython-39.pyc
  apps/Backend/__pycache__/apiCalls.cpython-39.pyc
  apps/Backend/__pycache__/dbpass.cpython-39.pyc
  apps/Backend/__pycache__/info.cpython-39.pyc
  apps/Backend/__pycache__/unitTesting.cpython-39.pyc
  apps/Backend/apiCalls.py
  apps/Backend/info.py
  apps/Backend/unitTesting.py
  requirements.txt
Labels: priority:high, Backend, CI/CD, Testing

#195 (Testing) : Integration
  apps/Backend/IntegrationTesting.py
  apps/Backend/__pycache__/AiFactor.cpython-39.pyc
Labels: Testing
